### ISSUE TITLE
redundant extends

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/sass-boilerplate#3]
I'm pretty sure %visible-sm is covered by Bootstrap see http://getbootstrap.com/css/#responsive-utilities-classes

Also, I'm not sure what %hideIconText does because it's referencing %offscreen which doesn't seem to exist but it sounds like it would do something similar to this: http://getbootstrap.com/css/#helper-classes-image-replacement

**Comment by soniktrooth** [comment]
@madeofpeople I'm happy to roll a PR just wanted to check first to make sure I'm not missing the use case for these.

**Comment by thiagodemellobueno** [comment]
You are right on these counts, roll it up, pack it in…

**Comment by soniktrooth** [comment]
https://www.youtube.com/watch?v=HNHjgd2k8l8

**Comment by soniktrooth** [comment]
Added PR at #4
